-- CreateEnum
CREATE TYPE "MaterialCategory" AS ENUM ('RAW_MATERIAL', 'MACHINE_PART', 'CONVEYOR_COMPONENT', 'OFFICE_SUPPLY', 'KITCHEN_SUPPLY', 'SAFETY_EQUIPMENT', 'CLEANING_SUPPLY', 'ELECTRICAL_COMPONENT', 'MECHANICAL_COMPONENT', 'OTHER');

-- AlterTable
ALTER TABLE "Material" ADD COLUMN     "category" "MaterialCategory" NOT NULL DEFAULT 'OTHER',
ADD COLUMN     "manufacturer" TEXT,
ADD COLUMN     "productSpecifications" JSONB;
